name: FCE Ultra GX Build

on: [push, pull_request]

jobs:
  build:
    name: ubuntu-20.04
    runs-on: ubuntu-20.04
    container: devkitpro/devkitppc:latest
 
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Build
      run: |
        make -j2
    
    - name: Copy files
      run: | 
        cp -f hbc/* executables/FCEUltraGX/apps/fceugx/
        cp -f hbc/* executables/FCEUltraGX-GameCube/
        cp -f README.md executables/FCEUltraGX/apps/fceugx/
        cp -f README.md executables/FCEUltraGX-GameCube/

    - name: Upload Wii Build Artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: FCEUltraGX-Nightly
        path: |
         executables/FCEUltraGX/
         !executables/FCEUltraGX/apps/fceugx/*.elf
    
    - name: Upload GameCube Build Artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: FCEUltraGX-Nightly-GameCube
        path: |
         executables/FCEUltraGX-GameCube/
         !executables/FCEUltraGX-GameCube/*.elf
